return {
    SeedsList = {
        "Carrot",
        "Strawberry",
        "Blueberry",
        "Orange Tulip",
        "Tomato",
        "Daffodil",
        "Watermelon",
        "Pumpkin",
        "Apple",
        "Bamboo",
        "Coconut",
        "Cactus",
        "Dragon Fruit",
        "Mango",
        "Grape",
        "Mushroom",
        "Pepper",
        "Cacao",
        "Beanstalk",
        "Ember Lily",
        "Sugar Apple",
        "Burning Bud",
        "Giant Pinecone"
    },
    GearsList = {
        "Watering Can",
        "Trowel",
        "Recall Wrench",
        "Basic Sprinkler",
        "Advanced Sprinkler",
        "Medium Toy",
        "Medium Treat",
        "Godly Sprinkler",
        "Magnifying Glass",
        "Tanning Mirror",
        "Master Sprinkler",
        "Cleaning Spray",
        "Favorite Tool",
        "Harvest Tool",
        "Friendship Pot",
        "Levelup Lollipop"
    },
    CosmeticList = {
        "Medium Wood Flooring",
        "Log",
        "Hay Bale",
        "Orange Umbrella",
        "Small Stone Table",
        "Wood Fecne",
        "Small Wood Flooring",
        "Large Wood Flooring",
        "Light On Ground",
        "Rake",
        "Orange Umbrella",
        "Medium Stone Table",
        "Wheelbarrow",
        "Grey Stone Pillar",
        "Frog Fountain",
        "Sign Crate",
        "Beach Crate"
    },
    EggsList = {
        "Common Egg",
        "Common Summer Egg",
        "Rare Summer Egg",
        "Mythical Egg",
        "Paradise Egg",
        "Bug Egg"
    },
    TravelingMerchantList = {
        "Night Staff",
        "Star Caller",
        "Mutation Spray Cloudtouched",
        
        "Flower Seed Pack",
        "Honey Sprinkler",
        "Bee Egg",
        "Bee Crate",
        "Honey Crafters Crate",

        "Common Gnome Crate",
        "Farmers Gnome Crate",
        "Classic Gnome Crate",
        "Iconic Gnome Crate",

        "Cauliflower",
        "Rafflesia",
        "Green Apple",
        "Avocado",
        "Banana",
        "Pineapple",
        "Kiwi",
        "Bell Pepper",
        "Prickly Pear",
        "Loquat",
        "Feijoa",
        "Pitcher Plant"
    },
    TreasuresList = {
        "Zen Seed Pack",
        "Zen Egg",
        "Hot Spring",
        "Zen Sand",
        "Zenflare",
        "Zen Crate",
        "Soft Sunshine",
        "Koi",
        "Zen Gnome Crate",
        "Spiked Mango",
        "Pet Shard Tranquil"
    }
}
